-- Meaux Theme Library - Complete Theme Seeding (v2 - matches actual schema)
-- All 40+ High-End Color Themes with Meaux/Inner Animal Branding
-- Run: wrangler d1 execute inneranimalmedia-business --file=src/seed-meaux-themes-v2.sql --remote

-- Note: This script uses INSERT OR REPLACE to update existing themes
-- Schema: id, name, display_name, description, is_custom, theme_data, config, is_active, is_public, category, slug, created_at, updated_at

-- ============================================
-- CLAY COLLECTION
-- ============================================

INSERT OR REPLACE INTO themes (id, name, display_name, description, is_custom, theme_data, config, is_active, is_public, category, slug, created_at, updated_at) VALUES
('theme-meaux-clay-light', 'meaux-clay-light', 'Meaux Clay Light', 'Soft claymorphism with light surfaces and gentle shadows', 0, '{"css_vars": {"--bg-surface": "#f7f8fa", "--bg-panel": "#ffffff", "--color-primary": "#2563eb", "--color-secondary": "#7c3aed", "--color-accent": "#06b6d4", "--color-text": "#0f172a", "--color-muted": "#64748b", "--color-border": "rgba(0, 0, 0, 0.08)", "--shadow-clay": "12px 12px 24px rgba(0, 0, 0, 0.08), -12px -12px 24px #ffffff", "--radius": "20px"}}', '{"colors": {"primary": "#2563eb", "secondary": "#7c3aed", "accent": "#06b6d4"}}', 1, 1, 'clay', 'meaux-clay-light', unixepoch(), unixepoch()),

('theme-meaux-clay-dark', 'meaux-clay-dark', 'Meaux Clay Dark', 'Dark claymorphism with deep surfaces and contrast shadows', 0, '{"css_vars": {"--bg-surface": "#1a1f2e", "--bg-panel": "#242938", "--color-primary": "#7c3aed", "--color-secondary": "#ec4899", "--color-accent": "#06b6d4", "--color-text": "#e2e8f0", "--color-muted": "#94a3b8", "--color-border": "rgba(255, 255, 255, 0.1)", "--shadow-clay": "8px 8px 16px rgba(0, 0, 0, 0.4), -8px -8px 16px rgba(255, 255, 255, 0.02)", "--radius": "20px"}}', '{"colors": {"primary": "#7c3aed", "secondary": "#ec4899", "accent": "#06b6d4"}}', 1, 1, 'clay', 'meaux-clay-dark', unixepoch(), unixepoch()),

-- ============================================
-- PREMIUM MODERN
-- ============================================

('theme-meaux-monochrome', 'meaux-monochrome', 'Meaux Monochrome', 'Clean monochrome design with elegant grayscale palette', 0, '{"css_vars": {"--bg-surface": "#ffffff", "--bg-panel": "#fafafa", "--color-primary": "#000000", "--color-secondary": "#171717", "--color-accent": "#404040", "--color-text": "#0a0a0a", "--color-muted": "#737373", "--color-border": "rgba(0, 0, 0, 0.1)", "--radius": "8px"}}', '{"colors": {"primary": "#000000", "secondary": "#171717", "accent": "#404040"}}', 1, 1, 'modern', 'meaux-monochrome', unixepoch(), unixepoch()),

('theme-meaux-workflow', 'meaux-workflow', 'Meaux Workflow', 'Dark productivity theme optimized for workflows', 0, '{"css_vars": {"--bg-surface": "#16181d", "--bg-panel": "#1c1f26", "--color-primary": "#5e6ad2", "--color-secondary": "#26b5ce", "--color-accent": "#95a2b3", "--color-text": "#e6edf3", "--color-muted": "#9ca3af", "--color-border": "rgba(255, 255, 255, 0.1)", "--radius": "12px"}}', '{"colors": {"primary": "#5e6ad2", "secondary": "#26b5ce", "accent": "#95a2b3"}}', 1, 1, 'productivity', 'meaux-workflow', unixepoch(), unixepoch()),

('theme-meaux-productivity', 'meaux-productivity', 'Meaux Productivity', 'Light theme designed for focused productivity', 0, '{"css_vars": {"--bg-surface": "#ffffff", "--bg-panel": "#f7f6f3", "--color-primary": "#eb5757", "--color-secondary": "#f2994a", "--color-accent": "#6fcf97", "--color-text": "#37352f", "--color-muted": "#9b9a97", "--color-border": "rgba(0, 0, 0, 0.06)", "--radius": "6px"}}', '{"colors": {"primary": "#eb5757", "secondary": "#f2994a", "accent": "#6fcf97"}}', 1, 1, 'productivity', 'meaux-productivity', unixepoch(), unixepoch()),

-- ============================================
-- APPLE ECOSYSTEM
-- ============================================

('theme-meaux-ios-light', 'meaux-ios-light', 'Meaux iOS Light', 'Apple-inspired light theme with iOS design language', 0, '{"css_vars": {"--bg-surface": "#f5f5f7", "--bg-panel": "#ffffff", "--color-primary": "#007aff", "--color-secondary": "#5856d6", "--color-accent": "#34c759", "--color-text": "#1d1d1f", "--color-muted": "#86868b", "--color-border": "rgba(0, 0, 0, 0.1)", "--radius": "18px"}}', '{"colors": {"primary": "#007aff", "secondary": "#5856d6", "accent": "#34c759"}}', 1, 1, 'apple', 'meaux-ios-light', unixepoch(), unixepoch()),

('theme-meaux-ios-dark', 'meaux-ios-dark', 'Meaux iOS Dark', 'Apple-inspired dark theme with iOS design language', 0, '{"css_vars": {"--bg-surface": "#000000", "--bg-panel": "#1c1c1e", "--color-primary": "#0a84ff", "--color-secondary": "#5e5ce6", "--color-accent": "#30d158", "--color-text": "#ffffff", "--color-muted": "#98989d", "--color-border": "rgba(255, 255, 255, 0.15)", "--radius": "18px"}}', '{"colors": {"primary": "#0a84ff", "secondary": "#5e5ce6", "accent": "#30d158"}}', 1, 1, 'apple', 'meaux-ios-dark', unixepoch(), unixepoch()),

-- ============================================
-- DEVELOPER TOOLS
-- ============================================

('theme-meaux-code-dark', 'meaux-code-dark', 'Meaux Code Dark', 'GitHub-inspired dark theme for developers', 0, '{"css_vars": {"--bg-surface": "#0d1117", "--bg-panel": "#161b22", "--color-primary": "#58a6ff", "--color-secondary": "#1f6feb", "--color-accent": "#79c0ff", "--color-text": "#c9d1d9", "--color-muted": "#8b949e", "--color-border": "rgba(240, 246, 252, 0.1)", "--radius": "6px"}}', '{"colors": {"primary": "#58a6ff", "secondary": "#1f6feb", "accent": "#79c0ff"}}', 1, 1, 'developer', 'meaux-code-dark', unixepoch(), unixepoch()),

('theme-meaux-browser', 'meaux-browser', 'Meaux Browser', 'Modern browser-inspired dark theme', 0, '{"css_vars": {"--bg-surface": "#1e1e1e", "--bg-panel": "#2a2a2a", "--color-primary": "#8b5cf6", "--color-secondary": "#ec4899", "--color-accent": "#06b6d4", "--color-text": "#ffffff", "--color-muted": "#a1a1aa", "--color-border": "rgba(255, 255, 255, 0.1)", "--radius": "16px"}}', '{"colors": {"primary": "#8b5cf6", "secondary": "#ec4899", "accent": "#06b6d4"}}', 1, 1, 'developer', 'meaux-browser', unixepoch(), unixepoch()),

('theme-meaux-design', 'meaux-design', 'Meaux Design', 'Bold design theme with vibrant colors', 0, '{"css_vars": {"--bg-surface": "#0a0a0a", "--bg-panel": "#1a1a1a", "--color-primary": "#0099ff", "--color-secondary": "#ff0080", "--color-accent": "#00ff99", "--color-text": "#ffffff", "--color-muted": "#999999", "--color-border": "rgba(255, 255, 255, 0.1)", "--radius": "12px"}}', '{"colors": {"primary": "#0099ff", "secondary": "#ff0080", "accent": "#00ff99"}}', 1, 1, 'creative', 'meaux-design', unixepoch(), unixepoch()),

('theme-meaux-creative', 'meaux-creative', 'Meaux Creative', 'Light creative theme for design work', 0, '{"css_vars": {"--bg-surface": "#ffffff", "--bg-panel": "#f5f5f5", "--color-primary": "#0d99ff", "--color-secondary": "#f24e1e", "--color-accent": "#0acf83", "--color-text": "#1e1e1e", "--color-muted": "#6e6e6e", "--color-border": "rgba(0, 0, 0, 0.1)", "--radius": "8px"}}', '{"colors": {"primary": "#0d99ff", "secondary": "#f24e1e", "accent": "#0acf83"}}', 1, 1, 'creative', 'meaux-creative', unixepoch(), unixepoch()),

('theme-meaux-knowledge', 'meaux-knowledge', 'Meaux Knowledge', 'Dark theme optimized for knowledge work', 0, '{"css_vars": {"--bg-surface": "#1e1e1e", "--bg-panel": "#2d2d2d", "--color-primary": "#7c3aed", "--color-secondary": "#8b5cf6", "--color-accent": "#a78bfa", "--color-text": "#dcddde", "--color-muted": "#b9bbbe", "--color-border": "rgba(255, 255, 255, 0.1)", "--radius": "8px"}}', '{"colors": {"primary": "#7c3aed", "secondary": "#8b5cf6", "accent": "#a78bfa"}}', 1, 1, 'productivity', 'meaux-knowledge', unixepoch(), unixepoch()),

('theme-meaux-galaxy', 'meaux-galaxy', 'Meaux Galaxy', 'Deep space galaxy theme with purple accents', 0, '{"css_vars": {"--bg-surface": "#0a0e14", "--bg-panel": "#12171f", "--color-primary": "#7c3aed", "--color-secondary": "#2563eb", "--color-accent": "#ec4899", "--color-text": "#e2e8f0", "--color-muted": "#94a3b8", "--color-border": "rgba(124, 58, 237, 0.2)", "--radius": "16px"}}', '{"colors": {"primary": "#7c3aed", "secondary": "#2563eb", "accent": "#ec4899"}}', 1, 1, 'dark', 'meaux-galaxy', unixepoch(), unixepoch()),

('theme-meaux-adaptive', 'meaux-adaptive', 'Meaux Adaptive', 'Adaptive Material Design-inspired theme', 0, '{"css_vars": {"--bg-surface": "#fef7ff", "--bg-panel": "#ffffff", "--color-primary": "#6750a4", "--color-secondary": "#7d5260", "--color-accent": "#006c4c", "--color-text": "#1c1b1f", "--color-muted": "#79747e", "--color-border": "rgba(0, 0, 0, 0.08)", "--radius": "16px"}}', '{"colors": {"primary": "#6750a4", "secondary": "#7d5260", "accent": "#006c4c"}}', 1, 1, 'modern', 'meaux-adaptive', unixepoch(), unixepoch()),

('theme-meaux-workspace', 'meaux-workspace', 'Meaux Workspace', 'Slack-inspired workspace theme', 0, '{"css_vars": {"--bg-surface": "#ffffff", "--bg-panel": "#f8f8f8", "--color-primary": "#611f69", "--color-secondary": "#1264a3", "--color-accent": "#2eb67d", "--color-text": "#1d1c1d", "--color-muted": "#616061", "--color-border": "rgba(0, 0, 0, 0.13)", "--radius": "8px"}}', '{"colors": {"primary": "#611f69", "secondary": "#1264a3", "accent": "#2eb67d"}}', 1, 1, 'productivity', 'meaux-workspace', unixepoch(), unixepoch()),

('theme-meaux-music', 'meaux-music', 'Meaux Music', 'Spotify-inspired dark music theme', 0, '{"css_vars": {"--bg-surface": "#121212", "--bg-panel": "#181818", "--color-primary": "#1db954", "--color-secondary": "#1ed760", "--color-accent": "#ffffff", "--color-text": "#ffffff", "--color-muted": "#b3b3b3", "--color-border": "rgba(255, 255, 255, 0.1)", "--radius": "8px"}}', '{"colors": {"primary": "#1db954", "secondary": "#1ed760", "accent": "#ffffff"}}', 1, 1, 'entertainment', 'meaux-music', unixepoch(), unixepoch()),

('theme-meaux-system', 'meaux-system', 'Meaux System', 'System default theme with Apple aesthetics', 0, '{"css_vars": {"--bg-surface": "#f5f5f7", "--bg-panel": "#ffffff", "--color-primary": "#007aff", "--color-secondary": "#34c759", "--color-accent": "#ff9500", "--color-text": "#1d1d1f", "--color-muted": "#86868b", "--color-border": "rgba(0, 0, 0, 0.1)", "--radius": "12px"}}', '{"colors": {"primary": "#007aff", "secondary": "#34c759", "accent": "#ff9500"}}', 1, 1, 'apple', 'meaux-system', unixepoch(), unixepoch()),

('theme-meaux-spatial', 'meaux-spatial', 'Meaux Spatial', 'Spatial computing theme with depth', 0, '{"css_vars": {"--bg-surface": "#000000", "--bg-panel": "#0a0a0a", "--color-primary": "#0a84ff", "--color-secondary": "#ffffff", "--color-accent": "#30d158", "--color-text": "#ffffff", "--color-muted": "#98989d", "--color-border": "rgba(255, 255, 255, 0.15)", "--radius": "20px"}}', '{"colors": {"primary": "#0a84ff", "secondary": "#ffffff", "accent": "#30d158"}}', 1, 1, 'apple', 'meaux-spatial', unixepoch(), unixepoch()),

('theme-meaux-editor', 'meaux-editor', 'Meaux Editor', 'VS Code-inspired editor theme', 0, '{"css_vars": {"--bg-surface": "#1e1e1e", "--bg-panel": "#252526", "--color-primary": "#007acc", "--color-secondary": "#0098ff", "--color-accent": "#4ec9b0", "--color-text": "#d4d4d4", "--color-muted": "#858585", "--color-border": "rgba(255, 255, 255, 0.1)", "--radius": "4px"}}', '{"colors": {"primary": "#007acc", "secondary": "#0098ff", "accent": "#4ec9b0"}}', 1, 1, 'developer', 'meaux-editor', unixepoch(), unixepoch()),

('theme-meaux-launcher', 'meaux-launcher', 'Meaux Launcher', 'App launcher theme with vibrant colors', 0, '{"css_vars": {"--bg-surface": "#1c1c1e", "--bg-panel": "#2c2c2e", "--color-primary": "#ff6363", "--color-secondary": "#30d158", "--color-accent": "#0a84ff", "--color-text": "#ffffff", "--color-muted": "#98989d", "--color-border": "rgba(255, 255, 255, 0.15)", "--radius": "12px"}}', '{"colors": {"primary": "#ff6363", "secondary": "#30d158", "accent": "#0a84ff"}}', 1, 1, 'productivity', 'meaux-launcher', unixepoch(), unixepoch()),

('theme-meaux-arctic', 'meaux-arctic', 'Meaux Arctic', 'Nord-inspired arctic theme', 0, '{"css_vars": {"--bg-surface": "#2e3440", "--bg-panel": "#3b4252", "--color-primary": "#88c0d0", "--color-secondary": "#81a1c1", "--color-accent": "#5e81ac", "--color-text": "#eceff4", "--color-muted": "#d8dee9", "--color-border": "rgba(216, 222, 233, 0.1)", "--radius": "8px"}}', '{"colors": {"primary": "#88c0d0", "secondary": "#81a1c1", "accent": "#5e81ac"}}', 1, 1, 'dark', 'meaux-arctic', unixepoch(), unixepoch()),

('theme-meaux-vampire', 'meaux-vampire', 'Meaux Vampire', 'Dracula-inspired vampire theme', 0, '{"css_vars": {"--bg-surface": "#282a36", "--bg-panel": "#44475a", "--color-primary": "#bd93f9", "--color-secondary": "#ff79c6", "--color-accent": "#8be9fd", "--color-text": "#f8f8f2", "--color-muted": "#6272a4", "--color-border": "rgba(98, 114, 164, 0.3)", "--radius": "8px"}}', '{"colors": {"primary": "#bd93f9", "secondary": "#ff79c6", "accent": "#8be9fd"}}', 1, 1, 'dark', 'meaux-vampire', unixepoch(), unixepoch()),

('theme-meaux-neon', 'meaux-neon', 'Meaux Neon', 'Tokyo Night-inspired neon theme', 0, '{"css_vars": {"--bg-surface": "#1a1b26", "--bg-panel": "#24283b", "--color-primary": "#7aa2f7", "--color-secondary": "#bb9af7", "--color-accent": "#7dcfff", "--color-text": "#c0caf5", "--color-muted": "#9aa5ce", "--color-border": "rgba(122, 162, 247, 0.2)", "--radius": "8px"}}', '{"colors": {"primary": "#7aa2f7", "secondary": "#bb9af7", "accent": "#7dcfff"}}', 1, 1, 'dark', 'meaux-neon', unixepoch(), unixepoch()),

('theme-meaux-solar', 'meaux-solar', 'Meaux Solar', 'Solarized dark theme', 0, '{"css_vars": {"--bg-surface": "#002b36", "--bg-panel": "#073642", "--color-primary": "#268bd2", "--color-secondary": "#2aa198", "--color-accent": "#859900", "--color-text": "#839496", "--color-muted": "#586e75", "--color-border": "rgba(131, 148, 150, 0.2)", "--radius": "6px"}}', '{"colors": {"primary": "#268bd2", "secondary": "#2aa198", "accent": "#859900"}}', 1, 1, 'dark', 'meaux-solar', unixepoch(), unixepoch()),

('theme-meaux-terminal', 'meaux-terminal', 'Meaux Terminal', 'Classic terminal green theme', 0, '{"css_vars": {"--bg-surface": "#0a0e14", "--bg-panel": "#12171f", "--color-primary": "#00ff00", "--color-secondary": "#33ff33", "--color-accent": "#00cc00", "--color-text": "#00ff00", "--color-muted": "#00aa00", "--color-border": "rgba(0, 255, 0, 0.2)", "--radius": "8px"}}', '{"colors": {"primary": "#00ff00", "secondary": "#33ff33", "accent": "#00cc00"}}', 1, 1, 'developer', 'meaux-terminal', unixepoch(), unixepoch()),

('theme-meaux-minimal', 'meaux-minimal', 'Meaux Minimal', 'Ultra-minimal grayscale theme', 0, '{"css_vars": {"--bg-surface": "#ffffff", "--bg-panel": "#fafafa", "--color-primary": "#000000", "--color-secondary": "#666666", "--color-accent": "#999999", "--color-text": "#000000", "--color-muted": "#666666", "--color-border": "rgba(0, 0, 0, 0.1)", "--radius": "8px"}}', '{"colors": {"primary": "#000000", "secondary": "#666666", "accent": "#999999"}}', 1, 1, 'modern', 'meaux-minimal', unixepoch(), unixepoch()),

-- ============================================
-- SPECIALTY THEMES
-- ============================================

('theme-meaux-glass-orange', 'meaux-glass-orange', 'Meaux Glass Orange', 'Glassmorphism with orange accent (Inner Animal signature)', 0, '{"css_vars": {"--bg-surface": "#ffffff", "--bg-panel": "rgba(255, 255, 255, 0.7)", "--color-primary": "#FF6B00", "--color-secondary": "#339999", "--color-accent": "#00D4FF", "--color-text": "#1a1a1a", "--color-muted": "#666666", "--color-border": "rgba(255, 255, 255, 0.3)", "--radius": "20px", "--glass-blur": "20px"}}', '{"colors": {"primary": "#FF6B00", "secondary": "#339999", "accent": "#00D4FF"}}', 1, 1, 'glass', 'meaux-glass-orange', unixepoch(), unixepoch()),

('theme-meaux-ops-dark', 'meaux-ops-dark', 'Meaux Ops Dark', 'Operations-focused dark theme', 0, '{"css_vars": {"--bg-surface": "#020617", "--bg-panel": "#0f172a", "--color-primary": "#00D4FF", "--color-secondary": "#0077FF", "--color-accent": "#8b5cf6", "--color-text": "#e2e8f0", "--color-muted": "#94a3b8", "--color-border": "rgba(0, 212, 255, 0.2)", "--radius": "16px"}}', '{"colors": {"primary": "#00D4FF", "secondary": "#0077FF", "accent": "#8b5cf6"}}', 1, 1, 'operations', 'meaux-ops-dark', unixepoch(), unixepoch()),

('theme-meaux-command', 'meaux-command', 'Meaux Command', 'Command-line inspired dark theme', 0, '{"css_vars": {"--bg-surface": "#0A0E14", "--bg-panel": "#12171F", "--color-primary": "#38BDF8", "--color-secondary": "#0EA5E9", "--color-accent": "#A855F7", "--color-text": "#E6EDF3", "--color-muted": "#8B949E", "--color-border": "rgba(56, 189, 248, 0.2)", "--radius": "12px"}}', '{"colors": {"primary": "#38BDF8", "secondary": "#0EA5E9", "accent": "#A855F7"}}', 1, 1, 'developer', 'meaux-command', unixepoch(), unixepoch()),

-- ============================================
-- INNER ANIMAL SIGNATURE THEMES
-- ============================================

('theme-inner-animal-light', 'inner-animal-light', 'Inner Animal Light', 'Inner Animal signature light theme', 0, '{"css_vars": {"--bg-surface": "#f8f9fa", "--bg-panel": "#ffffff", "--color-primary": "#2563eb", "--color-secondary": "#7c3aed", "--color-accent": "#ec4899", "--color-text": "#0f172a", "--color-muted": "#64748b", "--color-border": "rgba(0, 0, 0, 0.08)", "--radius": "16px"}}', '{"colors": {"primary": "#2563eb", "secondary": "#7c3aed", "accent": "#ec4899"}}', 1, 1, 'brand', 'inner-animal-light', unixepoch(), unixepoch()),

('theme-inner-animal-dark', 'inner-animal-dark', 'Inner Animal Dark', 'Inner Animal signature dark theme', 0, '{"css_vars": {"--bg-surface": "#0a0e14", "--bg-panel": "#12171f", "--color-primary": "#00D4FF", "--color-secondary": "#7c3aed", "--color-accent": "#ec4899", "--color-text": "#e2e8f0", "--color-muted": "#94a3b8", "--color-border": "rgba(0, 212, 255, 0.2)", "--radius": "16px"}}', '{"colors": {"primary": "#00D4FF", "secondary": "#7c3aed", "accent": "#ec4899"}}', 1, 1, 'brand', 'inner-animal-dark', unixepoch(), unixepoch()),

('theme-inner-animal-wild', 'inner-animal-wild', 'Inner Animal Wild', 'Bold Inner Animal theme with vibrant colors', 0, '{"css_vars": {"--bg-surface": "#1a1f2e", "--bg-panel": "#242938", "--color-primary": "#ec4899", "--color-secondary": "#f97316", "--color-accent": "#8b5cf6", "--color-text": "#ffffff", "--color-muted": "#a1a1aa", "--color-border": "rgba(236, 72, 153, 0.2)", "--radius": "20px"}}', '{"colors": {"primary": "#ec4899", "secondary": "#f97316", "accent": "#8b5cf6"}}', 1, 1, 'brand', 'inner-animal-wild', unixepoch(), unixepoch()),

('theme-inner-animal-zen', 'inner-animal-zen', 'Inner Animal Zen', 'Peaceful Inner Animal theme with calm colors', 0, '{"css_vars": {"--bg-surface": "#ffffff", "--bg-panel": "#fafafa", "--color-primary": "#10b981", "--color-secondary": "#06b6d4", "--color-accent": "#8b5cf6", "--color-text": "#1a1a1a", "--color-muted": "#737373", "--color-border": "rgba(0, 0, 0, 0.08)", "--radius": "12px"}}', '{"colors": {"primary": "#10b981", "secondary": "#06b6d4", "accent": "#8b5cf6"}}', 1, 1, 'brand', 'inner-animal-zen', unixepoch(), unixepoch()),

('theme-inner-animal-fire', 'inner-animal-fire', 'Inner Animal Fire', 'Fiery Inner Animal theme with warm tones', 0, '{"css_vars": {"--bg-surface": "#1a1614", "--bg-panel": "#2a2420", "--color-primary": "#f97316", "--color-secondary": "#dc2626", "--color-accent": "#fbbf24", "--color-text": "#fef3c7", "--color-muted": "#a0a0a0", "--color-border": "rgba(249, 115, 22, 0.2)", "--radius": "16px"}}', '{"colors": {"primary": "#f97316", "secondary": "#dc2626", "accent": "#fbbf24"}}', 1, 1, 'brand', 'inner-animal-fire', unixepoch(), unixepoch()),

('theme-inner-animal-ocean', 'inner-animal-ocean', 'Inner Animal Ocean', 'Oceanic Inner Animal theme with cool blues', 0, '{"css_vars": {"--bg-surface": "#0a1929", "--bg-panel": "#132f4c", "--color-primary": "#00b4d8", "--color-secondary": "#0077b6", "--color-accent": "#90e0ef", "--color-text": "#e0f2fe", "--color-muted": "#94a3b8", "--color-border": "rgba(0, 180, 216, 0.2)", "--radius": "16px"}}', '{"colors": {"primary": "#00b4d8", "secondary": "#0077b6", "accent": "#90e0ef"}}', 1, 1, 'brand', 'inner-animal-ocean', unixepoch(), unixepoch()),

-- ============================================
-- CYBER SERIES
-- ============================================

('theme-meaux-cyber-punk', 'meaux-cyber-punk', 'Meaux Cyber Punk', 'Cyberpunk 2077-inspired theme', 0, '{"css_vars": {"--bg-surface": "#0f0f23", "--bg-panel": "#1a1a2e", "--color-primary": "#ff006e", "--color-secondary": "#00f5ff", "--color-accent": "#ffbe0b", "--color-text": "#ffffff", "--color-muted": "#a0a0b0", "--color-border": "rgba(255, 0, 110, 0.3)", "--radius": "4px"}}', '{"colors": {"primary": "#ff006e", "secondary": "#00f5ff", "accent": "#ffbe0b"}}', 1, 1, 'cyber', 'meaux-cyber-punk', unixepoch(), unixepoch()),

('theme-meaux-neon-city', 'meaux-neon-city', 'Meaux Neon City', 'Neon city lights theme', 0, '{"css_vars": {"--bg-surface": "#0a0a0f", "--bg-panel": "#16161f", "--color-primary": "#ff00ff", "--color-secondary": "#00ffff", "--color-accent": "#ffff00", "--color-text": "#ffffff", "--color-muted": "#9090a0", "--color-border": "rgba(255, 0, 255, 0.3)", "--radius": "8px"}}', '{"colors": {"primary": "#ff00ff", "secondary": "#00ffff", "accent": "#ffff00"}}', 1, 1, 'cyber', 'meaux-neon-city', unixepoch(), unixepoch()),

('theme-meaux-synthwave', 'meaux-synthwave', 'Meaux Synthwave', 'Synthwave retro-futuristic theme', 0, '{"css_vars": {"--bg-surface": "#2b213a", "--bg-panel": "#241b35", "--color-primary": "#ff00aa", "--color-secondary": "#00d9ff", "--color-accent": "#ffd319", "--color-text": "#ffffff", "--color-muted": "#b8b8c8", "--color-border": "rgba(255, 0, 170, 0.3)", "--radius": "12px"}}', '{"colors": {"primary": "#ff00aa", "secondary": "#00d9ff", "accent": "#ffd319"}}', 1, 1, 'cyber', 'meaux-synthwave', unixepoch(), unixepoch()),

('theme-meaux-hacker-green', 'meaux-hacker-green', 'Meaux Hacker Green', 'Matrix-style hacker green theme', 0, '{"css_vars": {"--bg-surface": "#000000", "--bg-panel": "#0a0f0a", "--color-primary": "#00ff41", "--color-secondary": "#00cc33", "--color-accent": "#39ff14", "--color-text": "#00ff41", "--color-muted": "#00aa2b", "--color-border": "rgba(0, 255, 65, 0.2)", "--radius": "6px"}}', '{"colors": {"primary": "#00ff41", "secondary": "#00cc33", "accent": "#39ff14"}}', 1, 1, 'cyber', 'meaux-hacker-green', unixepoch(), unixepoch()),

('theme-meaux-matrix-rain', 'meaux-matrix-rain', 'Meaux Matrix Rain', 'Matrix digital rain theme', 0, '{"css_vars": {"--bg-surface": "#000000", "--bg-panel": "#001a00", "--color-primary": "#00ff00", "--color-secondary": "#00dd00", "--color-accent": "#33ff33", "--color-text": "#00ff00", "--color-muted": "#00bb00", "--color-border": "rgba(0, 255, 0, 0.3)", "--radius": "4px"}}', '{"colors": {"primary": "#00ff00", "secondary": "#00dd00", "accent": "#33ff33"}}', 1, 1, 'cyber', 'meaux-matrix-rain', unixepoch(), unixepoch()),

('theme-meaux-midnight-blue', 'meaux-midnight-blue', 'Meaux Midnight Blue', 'Deep midnight blue theme', 0, '{"css_vars": {"--bg-surface": "#0c1445", "--bg-panel": "#1a2456", "--color-primary": "#4d7cfe", "--color-secondary": "#7b68ee", "--color-accent": "#00bfff", "--color-text": "#e0e7ff", "--color-muted": "#9ca3c0", "--color-border": "rgba(77, 124, 254, 0.2)", "--radius": "16px"}}', '{"colors": {"primary": "#4d7cfe", "secondary": "#7b68ee", "accent": "#00bfff"}}', 1, 1, 'cyber', 'meaux-midnight-blue', unixepoch(), unixepoch()),

('theme-meaux-sunset-glow', 'meaux-sunset-glow', 'Meaux Sunset Glow', 'Warm sunset glow theme', 0, '{"css_vars": {"--bg-surface": "#1a0f0a", "--bg-panel": "#2a1f1a", "--color-primary": "#ff6b35", "--color-secondary": "#f7931e", "--color-accent": "#ffd60a", "--color-text": "#fff5e6", "--color-muted": "#c0a090", "--color-border": "rgba(255, 107, 53, 0.2)", "--radius": "20px"}}', '{"colors": {"primary": "#ff6b35", "secondary": "#f7931e", "accent": "#ffd60a"}}', 1, 1, 'nature', 'meaux-sunset-glow', unixepoch(), unixepoch()),

('theme-meaux-forest-deep', 'meaux-forest-deep', 'Meaux Forest Deep', 'Deep forest green theme', 0, '{"css_vars": {"--bg-surface": "#0a1f0f", "--bg-panel": "#1a2f1f", "--color-primary": "#2ecc71", "--color-secondary": "#27ae60", "--color-accent": "#52c41a", "--color-text": "#e8f5e9", "--color-muted": "#90b090", "--color-border": "rgba(46, 204, 113, 0.2)", "--radius": "14px"}}', '{"colors": {"primary": "#2ecc71", "secondary": "#27ae60", "accent": "#52c41a"}}', 1, 1, 'nature', 'meaux-forest-deep', unixepoch(), unixepoch()),

('theme-meaux-desert-sand', 'meaux-desert-sand', 'Meaux Desert Sand', 'Warm desert sand theme', 0, '{"css_vars": {"--bg-surface": "#2a1f15", "--bg-panel": "#3a2f25", "--color-primary": "#d4a574", "--color-secondary": "#c19a6b", "--color-accent": "#f4a460", "--color-text": "#fef5e7", "--color-muted": "#b09070", "--color-border": "rgba(212, 165, 116, 0.2)", "--radius": "18px"}}', '{"colors": {"primary": "#d4a574", "secondary": "#c19a6b", "accent": "#f4a460"}}', 1, 1, 'nature', 'meaux-desert-sand', unixepoch(), unixepoch()),

('theme-meaux-storm-gray', 'meaux-storm-gray', 'Meaux Storm Gray', 'Stormy gray theme with blue accents', 0, '{"css_vars": {"--bg-surface": "#1c1c1e", "--bg-panel": "#2c2c2e", "--color-primary": "#5ac8fa", "--color-secondary": "#64d2ff", "--color-accent": "#30d5c8", "--color-text": "#f2f2f7", "--color-muted": "#98989d", "--color-border": "rgba(90, 200, 250, 0.2)", "--radius": "12px"}}', '{"colors": {"primary": "#5ac8fa", "secondary": "#64d2ff", "accent": "#30d5c8"}}', 1, 1, 'modern', 'meaux-storm-gray', unixepoch(), unixepoch());
